### ISSUE TITLE
java-0.3.4 release doesn't build with --locked

### ISSUE THREAD

**Issue by svmhdvn** [signalapp/libsignal#248]
I think the Cargo.lock file might be out of date on this tag. Master builds fine with `--locked`, but java-0.3.4 doesn't:

```
error: the lock file /home/siva/src/aports/testing/libsignal-client/src/libsignal-client-java-0.3.4/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

Could you release a new `java-` tag that updates this?

**Comment by jack-signal** [comment]
Thanks for pointing this out. I don't think we are going to do a new Java release just to resolve this one issue, but we should start using `--locked` in our CI builds so this doesn't recur in the future.
