### ISSUE TITLE
"libsignal_jni.so" not found

### ISSUE THREAD

**Issue by ahmedcs2600** [signalapp/libsignal#372]
I am trying to run Signal Java Library in my android Project & I am getting the exception 
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsignal_jni.so" not found
I have imported this library in my build.gradle(app)
    implementation 'org.whispersystems:signal-client-java:0.9.6'

**Comment by jatin-lakhani** [comment]
+1

**Comment by ahmedcs2600** [comment]
signal-client-android is not working with cross-platform end-end encryption. I have checked signal-client-java in the signal open source app and it's working with cross-platform. So I just need to install signal-client-java in my project

**Comment by marinat** [comment]
Are signal-client-android and signal-client-java deprecated? There are no new updates. I imported the library into toml like this:
libsignal-client = { module = "org.signal:libsignal-client", version.ref = "0.35.0" }
