### ISSUE TITLE
Synchronization betwen destop app and anroid ansdios app do not work

### ISSUE THREAD

**Issue by MarkoGolemovic** [signalapp/libsignal#387]
Sincroniyattion between different platform do not work.

**Comment by jrose-signal** [comment]
Can you file this issue with our Support team at <https://support.signal.org/hc/en-us/requests/new> ? It would also be helpful if you can submit [debug logs](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) from each of your devices.
