### ISSUE TITLE
Not build archive - Invalid value (Producer: 'LLVM13.0.0-rust-1.57.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64

### ISSUE THREAD

**Issue by ivanking87** [signalapp/libsignal#437]
When I want create Archive deploy I have this error from SignalClient lib
Invalid value (Producer: 'LLVM13.0.0-rust-1.57.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64

**Comment by jrose-signal** [comment]
How are you trying to build your app? The usual way we build the iOS app uses prebuilt artifacts in the [Signal-Pods](/signalapp/Signal-Pods) repo, though those artifacts are still built through `pod install` (just in a more controlled environment).
