### ISSUE TITLE
Post-Quantum Cryptography

### ISSUE THREAD

**Issue by Qata** [signalapp/libsignal#465]
I was reading [The Post-Quantum Signal Protocol](https://essay.utwente.nl/77239/1/Duits_MA_EEMCS.pdf) and was just wondering if there's any roadmap plans to move the library in a post-quantum direction.

I know we're still a far cry from widespread cryptography breaking, so I'm just asking this for visibility on what timelines will be, if there are any at all.

**Comment by ehrenkret-signal** [comment]
We do not have any post-quantum timelines to share at this time, but we are watching the space closely (in particular the PQ-KEM standardization process) and will update the Signal Protocol appropriately to deal with this issue.

**Comment by igor-krawczuk** [comment]
Relevant talk from the rc3 would indicate classic mceliece is safer from a patent perspective for a quick rollout https://www.youtube.com/watch?v=taZfUOpUc6E

**Comment by plutoniumm** [comment]
Now that the signal protocol has added Khyber to their specification, I would assume this issue is relevant again?

[PQXDH](https://signal.org/docs/specifications/pqxdh/)

**Comment by ston1th** [comment]
I'm no expert by any means but is this post from DJB regarding the NISTs selection process for Kyber somehow relevant on the choice of algorithms for PQXDH?

https://blog.cr.yp.to/20231003-countcorrectly.html

**Comment by loganaden** [comment]
@ehrenkret-signal why not tweak the specs to allow non-NIST Kex like NTRU Prime ? OpenSSH 9.0 defaults to a hybrid with ntru prime and there hasn't been known weaknesses so far.

**Comment by jrose-signal** [comment]
Just clearing this up: the [spec](https://signal.org/docs/specifications/pqxdh/) says

> A post-quantum key encapsulation mechanism that has IND-CCA post-quantum security (e.g. Crystals-Kyber-1024)

Another implementation of PQXDH can certainly choose to use a KEM other than Kyber.
