### ISSUE TITLE
CentOs 7

### ISSUE THREAD

**Issue by HoffmannP** [signalapp/libsignal#498]
Hy,

I'd like to use libsingal in CentOs 7 but I can't seem to install it. I'd need GLIBC_2.28 for the compiled version or CMake 3.5 to compile it myself. Has anyone any advice how to use it anyway?

Best wishes
H0ffman

**Comment by jrose-signal** [comment]
I haven't tried it but it looks like the `cmake3` package on CentOS has a new enough version of CMake. You may need to then (temporarily) make it findable as `cmake`, as described in [these StackOverflow answers](https://stackoverflow.com/questions/48831131/cmake-on-linux-centos-7-how-to-force-the-system-to-use-cmake3), though it would be nice™ if cmake-rs magically found `cmake3`. Please report back if this works for you!

**Comment by HoffmannP** [comment]
Hey @jrose-signal
thanks for the helpful reply, using cmak3 as a replacement worked pretty fine!
But now I run into the next version error as "This crate" ( I assume signalapp/boring)  requires `libclang 3.9`.

**Comment by jrose-signal** [comment]
That's correct, you'll need to find a way to get a newer version of Clang as well.

(I know we don't document our minimum dependencies very well, but at the same time any use outside of what Signal does is "unsupported" in some sense.)
