### ISSUE TITLE
could not build on react-native

### ISSUE THREAD

**Issue by monkeyWie** [signalapp/libsignal#500]
Is there a way to run on react-natice? 
```
error: Error: Unable to resolve module os from d:\code\study\node\gali\node_modules\node-gyp-build\index.js: os could not be found within the project or in these directories:
  node_modules
  1 | var fs = require('fs')
  2 | var path = require('path')
  3 | var os = require('os')
```

**Comment by jrose-signal** [comment]
The only supported platform is Electron, as used by the official Signal Desktop client. However, the use of node-gyp-build is mostly just to make sure the N-API-based Rust modules get built and loaded properly; if that's the only incompatibility with React-Native, it's possible you could skip the install script and get everything to work. Patches welcome as long as they don't cause an undue maintainence burden.

**Comment by monkeyWie** [comment]
Thank you for reply, I have rethought it, react-native not support NAPI, so this should not be possible, unless this is written in pure js.

**Comment by ajitdas123** [comment]
@monkeyWie Did you find a way to use this library?  or are you using any other for E2E encryption?

**Comment by monkeyWie** [comment]
@ajitdas123 no, but you can consider platform native module.
