### ISSUE TITLE
Can`t create swift local build

### ISSUE THREAD

**Issue by Invariant0x** [signalapp/libsignal#502]
I do everything according to the instructions my processor m2

swift/build_ffi.sh --generate-ffi

<img width="1211" alt="Screenshot 2022-12-16 at 12 03 45 AM" src="https://user-images.githubusercontent.com/117004236/207956402-d4df4fa7-f8d5-45bf-a368-b3d58cf81afa.png">

**Comment by jrose-signal** [comment]
I'm guessing you're using SwiftPM to bring in LibSignalClient to your project; this [isn't officially supported](https://github.com/signalapp/libsignal/tree/main/swift#use-as-a-swift-package). You can probably make it work by manually linking to libsignal.a within the target/ folder, as the SwiftPM test target does using `unsafeFlags`, but our real recommendation is to use it as a CocoaPod instead.

**Comment by Invariant0x** [comment]
I have this file in my debug folder - libsignal_ffi.a do you mean that I need to link it?
Please be more specific, I really need your help.

**Comment by jrose-signal** [comment]
If the brief instructions I gave are unclear, you should stick to the supported approach of using CocoaPods.
