### ISSUE TITLE
Anonymous Accounts on Signal

### ISSUE THREAD

**Issue by matchcom-cahors** [signalapp/libsignal#505]
I have been using Signal for some time now and I have noticed that there is currently no option for anonymous accounts. I believe that this feature would be greatly beneficial for users who are concerned about their privacy and want to keep their personal information separate from their messaging activity.

There are several other messaging apps that offer anonymous accounts and I think Signal should consider adding this feature as well. Anonymous accounts would allow users to protect their personal information and give them more control over their privacy.

It would be great if Signal could provide an option for users to create anonymous accounts, either through a separate registration process or by allowing them to create a temporary account without providing any personal information.

This feature could be especially useful for people who want to use Signal for activism, whistle-blowing or just avoid being tracked by advertisers.

I would appreciate your feedback on this idea and I would like to know if this feature is already in development or if there are any plans to implement it in the future.

**Comment by jrose-signal** [comment]
This sort of request is best directed to https://support.signal.org/, or the unofficial community forums at https://community.signalusers.org/. libsignal is a library used in the development of Signal, but the direction of the service as a whole is not decided here.
