### ISSUE TITLE
LIBSIGNAL_FFI_PREBUILD_CHECKSUM

### ISSUE THREAD

**Issue by Invariant0x** [signalapp/libsignal#506]
I can't find where i can see this checksum? 
This site  **build-artifacts.signal.org**  doesn`t work
Please help

**Comment by jrose-signal** [comment]
Sorry! I'll look into getting it into the GitHub Release, either as an appended note or an additional attached file. For v0.22.0 the checksum is ** 3fd72aa93ddf582f0aaecc3e649081df36ae562f5be22d18b69d2d3233bfbe96**, and Signal-iOS should be adopting it soon.

**Comment by palibodatanja** [comment]
> I can't find where i can see this checksum? 
> This site  **build-artifacts.signal.org**  doesn`t work
> Please help

**Comment by jrose-signal** [comment]
v0.23.0 properly has an attached file with the checksum!
