### ISSUE TITLE
Formal verification on the Rust code of Signal

### ISSUE THREAD

**Issue by clarus** [signalapp/libsignal#510]
Hello,

How can we help apply formal verification techniques on the Rust code of Signal? What would be a good way to start / would that be of interest for Signal?

For now we are looking at the verification of the [Subtle](https://github.com/dalek-cryptography/subtle) library from a kind suggestion of @cosmicexplorer , to check that all primitives execute in constant time. This is a training example of our project [coq-of-rust](https://github.com/formal-land/coq-of-rust) to verify existing Rust code without modifications. Thanks.

Guillaume for [Formal Land](https://formal.land/)

**Comment by jrose-signal** [comment]
Hi! This isn't something we're directly interested in at this time, but feel free to discuss it with the community on the unofficial forums at https://community.signalusers.org/.
