### ISSUE TITLE
It's unclear when a domain is clickable as a URL

### ISSUE THREAD

**Issue by mdavids** [signalapp/libsignal#511]
When I type example.nl, Signal turns it (as intended) into a clickable URL.

Not so much for some other attempts, like: fryslan.frl or https://xn--i-7iq.ws (https://i❤.ws) or https://аррӏе.com (which is in fact https://www.xn--80ak6aa92e.com/).

Based on what is this decided? Should the logic that does this be revised?

It's confusing now.

UPDATE: related to https://github.com/signalapp/Signal-Desktop/issues/4538 albeit that the issue is not limited to the Desktop app and also IDN's are not covered.

**Comment by jrose-signal** [comment]
Hello! This repository only covers specific features shared across Signal's three platforms, whereas "linkification" is currently done using platform-specific APIs. I think it makes sense to track the issue separately for each app where you've seen the problem.

That particular Desktop issue is closed, so can you please refile in the individual app repositories where you've seen this issue? Sorry for the inconvenience.

**Comment by mdavids** [comment]
https://github.com/signalapp/Signal-iOS/issues/5543
