### ISSUE TITLE
Register without transfer to new Signal client

### ISSUE THREAD

**Issue by PennyBristow** [signalapp/libsignal#516]
Working with the open-source code to integrate Signal.  We have been testing by using the Register without transfer as in our users case they will have Signal natively installed on the same phone as our client is on.   We were under the assumption that messages would not be transferred but we are getting notifications on OLD messages for some reason. (iOS).    

Im just trying to validate what truly will appear as we see contacts, as well as groups and were under the impression those would not port over either.  (basically, a net new start, is what we expected).   Is this incorrect?

**Comment by jrose-signal** [comment]
This repo isn't the best place to ask these sorts of questions; the library is a dependency for the main Signal apps, but does not include the business logic or communication with the server. General questions about interoperating with the official Signal service (unsupported!) are probably best asked on the unofficial forums, <https://community.signalusers.org>.

That said, if you want a full "clean slate" on re-registering, you should *not* provide your PIN. That will avoid restoring any of your previous account info upon registration.
