### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Andrii256** [signalapp/libsignal#518]
Hi
Maybe I'm a bit unnatended, but I didnt saw place in documentation when I can get info about that.

So.
I created few signal chats for different type of reports. I mean each chat is for special type of reports.
Its comfortable for me, because I can scroll and find notes which I need.

But. For security reason I need to clean my chatting history. But. I would like to save my notes somewhere in my pc.

I am familiar with javascript and with typescript.

**Are there any way for me to kinda download my messaging history from my specific chats?**

**Comment by jrose-signal** [comment]
Sorry, the Issues for this repository are specifically about **lib**signal, the library implementing some of Signal's underlying functionality. Feature requests should be made through [Support](https://support.signal.org/hc/en-us/requests/new), and you can discuss "unofficial" solutions on the [community forums](https://community.signalusers.org/).
