### ISSUE TITLE
Building fails with "This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set"

### ISSUE THREAD

**Issue by JsBergbau** [signalapp/libsignal#523]
When trying to build with `./build_jni.sh desktop` build process fails with 

```
Compiling libsignal-protocol v0.1.0 (/home/pi/Apps/libsignal-client/rust/protocol)
error: failed to run custom build command for `libsignal-protocol v0.1.0 (/home/pi/Apps/libsignal-client/rust/protocol)`

Caused by:
  process didn't exit successfully: `/home/pi/Apps/libsignal-client/target/release/build/libsignal-protocol-b8c4717a42f20850/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Protobufs in src are valid: Custom { kind: Other, error: "protoc failed: proto/storage.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }', rust/protocol/build.rs:14:52
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
using commit [a196fb8](https://github.com/signalapp/libsignal/commit/a196fb8ecd6be3b8d713841836f8535b71ee0835) but also the same problem with the commit from a few days ago.

**Comment by jrose-signal** [comment]
Hm, things are working fine for me with protoc 3.21.12. What version of protoc do you have installed?

**Comment by JsBergbau** [comment]
3.12.4 installed via `sudoapt install protobuf-compiler` on Debian 11. Looks like I have to do a manual install as described here https://grpc.io/docs/protoc-installation/

**Comment by JsBergbau** [comment]
Or where can I add the `--experimental_allow_proto3_optional` option in the build script?

**Comment by jrose-signal** [comment]
You know, our Dockerized Java build is using a Debian 10 image, and doesn't install protobuf-compiler. If you unset `PROTOC` in your environment, will it use the version bundled with prost-build?

(This workaround won't work forever; newer versions of prost-build do not include a bundled protobuf-compiler, and we will eventually update to them.)

**Comment by JsBergbau** [comment]
There is no PROTOC environment variable set. I had to install it via `sudoapt install protobuf-compiler`, so it didn't seem to use the bundled version.
When uninstalling protobuf-compiler I get, as expected
```
thread 'main' panicked at 'Protobufs in src are valid: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', rust/protocol/build.rs:14:52
```

For better understanding: I'm only trying to compile libsignal for signal-cli as explained here https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal 

I am on armv6 (Raspberry PI Zero W) and I didn't find a prebuild library for armv6 so I try to compile myself. This had worked more than one year ago, but since some time I am not receiving messages any more probably because of the outdated library, so I am now trying to update it.

**Comment by jrose-signal** [comment]
Obligatory "we don't officially support use outside of Signal's official clients", but then I'll note that libsignal is generally not perfectly compatible between releases (that's what the leading "0" in the version is supposed to indicate), and so compiling a newer version than what signal-cli expects will probably lead to crashes.

I think ultimately it is not a major goal of libsignal to remain compatible with older development tools than what the organization uses to build the Signal apps, and so installing protobuf from source is your best bet. Or cross-compiling from a newer system.

**Comment by JsBergbau** [comment]
Installation from source is also not an easy task, since for protoc you need bazel to build and that makes also a lot of trouble, so: Can you give me a hint what has to be done to crosscompile libsignal? I mean I have crosscompiled before and signal-cli/libsignal are the cause that there is now a JDK17 available for Raspberry PI Zero (W) / armv6 https://github.com/raspberrypi/linux/issues/3306
So I just need some point where to start. Your help is really appreciated.

**Comment by jrose-signal** [comment]
I found some general instructions for [cross-compiling Rust for RasPi systems](https://chacin.dev/blog/cross-compiling-rust-for-the-raspberry-pi/) that look correct to me; the target name is `libsignal-jni`, which you can see in `build_jni.sh`.

I'm going to close this issue because I don't think there's any action for Signal to take, but I'll answer questions a bit longer too. Like I said, though, I strongly suspect you'll get to the end of this and then find out that it doesn't work the current version of signal-cli.

**Comment by JsBergbau** [comment]
Thanks for the hint with `CC=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-gcc` that is definitely a better solution. I didn't like the symlink solution neither, at least I was glad to get it compiled.
Still with the CC env variable set it seems it requires another addition, because now it fails with linking

```
Compiling libsignal-jni v0.23.1 (/home/pi/libsignal-client/rust/bridge/jni)
error: linking with `cc` failed: exit status: 1

[a lot of line with the args of cc omitted]

  = note: /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: relocations in generic ELF (EM: 40)
          /usr/bin/ld: /home/pi/libsignal-client/target/arm-unknown-linux-gnueabihf/release/deps/signal_jni.3la2dkqjlmz1h0v6.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status


error: could not compile `libsignal-jni` due to previous error
```

**Comment by jrose-signal** [comment]
Ah, your `CARGO_TARGET_ARM_LINUX_GNUEABIHF_LINKER` should be `CARGO_TARGET_ARM_`**`UNKNOWN`**`_LINUX_GNUEABIHF_LINKER`

**Comment by JsBergbau** [comment]
Thank you very much. It works now and I've edited the post above.
Where did you find the name of the env variable `CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER` I was searching for documentation but did only find here https://doc.rust-lang.org/cargo/reference/environment-variables.html 
```
CARGO_TARGET_<triple>_LINKER — The linker to use, see [target.<triple>.linker](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker). The triple must be [converted to uppercase and underscores](https://doc.rust-lang.org/cargo/reference/config.html#environment-variables).
```
and https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker
```
[target.<triple>.linker](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker)

    Type: string (program path)
    Default: none
    Environment: CARGO_TARGET_<triple>_LINKER

Specifies the linker which is passed to rustc (via [-C linker](https://doc.rust-lang.org/rustc/codegen-options/index.html#linker)) when the [<triple>](https://doc.rust-lang.org/cargo/appendix/glossary.html#target) is being compiled for. By default, the linker is not overridden.
```
To be exact this is no triple anymore, but a quadruple ;)

**Comment by jrose-signal** [comment]
That's the correct documentation, yes. The "triple" comes from the Rust platform target name (from [this big list](https://doc.rust-lang.org/rustc/platform-support.html)), and yeah, it hasn't been a "triple" for a long time. ([Coincidentally, there was just a thread on the Swift forums about this.](https://forums.swift.org/t/what-exactly-is-a-triple-and-how-is-it-different-from-a-platform/65111))

**Comment by JsBergbau** [comment]
Crosscompiling boring-sys is still an issue. The workaround with symlink is still needed. I've added the steps again 
https://github.com/signalapp/libsignal/issues/523#issuecomment-1562970981

**Comment by lokeshjlr** [comment]
Similarly, I am getting following error in aosp build which is using .proto file to generate library:
**Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.**

I am not sure how can I enable 'optional' tag with Android.bp. Any help would be really appreciated.

**Comment by jrose-signal** [comment]
As time goes on, we're less and less interested in supporting old versions of protoc that don't know about proto3 and `optional`. You'll have to substitute a newer version of protoc in your build, which is not something we can help you with.
