### ISSUE TITLE
Sending Messages Programmatically?

### ISSUE THREAD

**Issue by olfek** [signalapp/libsignal#528]
Can this library be used to send messages programmatically?

I'm looking for something similar to:

 - https://developers.facebook.com/docs/whatsapp/api/messages/text
 - https://www.twilio.com/docs/verify/whatsapp
 - https://www.twilio.com/docs/whatsapp
 - https://aws.amazon.com/blogs/messaging-and-targeting/send-whatsapp-messages-via-amazon-pinpoint

**Comment by Max-Stirner-Signal** [comment]
This isn't something we officially support, as this is just used as a support library for Signal's apps.

In the future, we encourage you to visit our [Community Forum](https://community.signalusers.org/) with questions like these. Thanks!
