### ISSUE TITLE
Checksum for CocoaPods?

### ISSUE THREAD

**Issue by enricgd** [signalapp/libsignal#529]
Hi there,

I am unable to find the checksum for the iOS library in order to put where it needs to be in the cocoa installation.
In the link that it sends you to, there is no checksum in the notes.

Thanks

**Comment by jrose-signal** [comment]
v0.28.1 was a Java-only release, since there were no changes for iOS or Electron. [You can find the checksum for v0.28.0 as an attachment on the release.](https://github.com/signalapp/libsignal/releases/tag/v0.28.0)
