### ISSUE TITLE
Story Notifications

### ISSUE THREAD

**Issue by dsokoloski** [signalapp/libsignal#531]
### Notifications for Stories

Love the feature and I've been trying to use it quite often.  The problem is no one sees anything I post.  Turns out, Stories on Signal doesn't actually notify anyone you've shared them with.  So, unless contacts are actually aware that Stories exist, and regularly check for a red dot, no one will actually see them.

Great feature that no one knows about.

Please send (by default, with the option to disable) push notifications when a contact posts to a Story.

**Comment by jrose-signal** [comment]
Hi! This repository contains a library that supports the Signal apps; feature requests for the apps in general should go to <https://support.signal.org/>. We'll collect your feedback there. Thank you!
