### ISSUE TITLE
Where can the source code for signal_kyber_key_pair_generate (and other KEM functions) be found?

### ISSUE THREAD

**Issue by epoberezkin** [signalapp/libsignal#536]
https://github.com/search?q=org%3Asignalapp%20signal_kyber_key_pair_generate&type=code

**Comment by jrose-signal** [comment]
Good question. These functions are generated by the [`bridge_fn` helper macro](https://github.com/signalapp/libsignal/blob/main/rust/bridge/shared/macros/src/lib.rs) from declarations in the [libsignal-bridge crate](https://github.com/signalapp/libsignal/blob/main/rust/bridge/shared/src/protocol.rs#L251).

**Comment by epoberezkin** [comment]
Thank you!
