### ISSUE TITLE
Integration using swift in XCode

### ISSUE THREAD

**Issue by joesteen2135** [signalapp/libsignal#546]
So I have been trying to integrate the signal protocol on a basic level to a XCode project, however I cannot seem to find any documentation on how to actually implement creation of seesions, sending messages, decrypting messages, ect.

Is there any simplistic boilerplate on how to do basic things, as the only tutorials I found were extremely out of date?

**Comment by jrose-signal** [comment]
Not really, I'm afraid. libsignal is a library for Signal-the-app first, so integration from the ground up isn't something we spend a lot of time on. That said, if you have specific questions you can ask at <https://community.signalusers.org/> and might get good answers there.

I'm going to close this in favor of the longstanding #152; if there were high-level docs on how to use libsignal, they ought to cover what you're asking here!
