### ISSUE TITLE
Exclude unnecessary libraries from apk

### ISSUE THREAD

**Issue by marinat** [signalapp/libsignal#548]
When I build apk file with signal lib it contains libsignal_jni.dylib and signal_jni.dll, how to exclude them?

**Comment by jrose-signal** [comment]
Oh, good catch. You can and should add them to your `packagingOptions.resources.excludes`, as the official Android app does here:

https://github.com/signalapp/Signal-Android/blob/e17b07bb12110c0ebeae193cb6fad35d33b57d40/app/build.gradle.kts#L148-L152

I'll leave this issue open to add that to the doc files within libsignal.

**Comment by jrose-signal** [comment]
Readme updated in v0.38.0 with a mention of the Maven Central artifacts and the `exclude` options. Thanks for pointing this out!
