### ISSUE TITLE
How to generate and retrieve Registration Id , prekeyID etc. and encryption,decryption process .

### ISSUE THREAD

**Issue by RajenderReddyA** [signalapp/libsignal#551]
We are currently integrating this library into an Android chat messaging application and are facing challenges in understanding the process of generating and retrieving essential identifiers for encryption and decryption.

**Key Points:**

**Registration ID and preKey ID Retrieval:**
We are unsure about how to generate and retrieve the Registration ID, preKey ID, and other required key identifiers crucial for encryption and decryption in the Android environment.

**Message Encryption Process:**
We seek guidance on utilizing these identifiers and other pertinent information to encrypt message content. Specifically:

What functions are available for encryption?
What parameters need to be passed during encryption?
How do we generate these parameters, including remote address, session store, and prestore?      
                                                              
**Request for Assistance:**
We would greatly appreciate any help or guidance you can provide to help us achieve these objectives. Additionally, if there is documentation available that covers these aspects, please share it with us.

Thank you for your support.

**Comment by jrose-signal** [comment]
I'm afraid we don't have real high-level docs, as covered by the longstanding #152. libsignal is a library for Signal-the-app first, so integration from the ground up isn't something we spend a lot of time on. That said, this question would be a good fit for the Development section of https://community.signalusers.org/.
