### ISSUE TITLE
Message Encryption

### ISSUE THREAD

**Issue by DeepthiJonnagadla** [signalapp/libsignal#552]
We are currently working on integrating a library into our Swift chat messaging application to generate keys at the user's end. We need assistance with storing these keys and encrypting messages using them. 

We came across the "signalEncrypt" function for message encryption, but it requires session store and identity store details. Could you please guide us on where we can obtain these details?

We would appreciate any help or guidance you can provide to help us achieve our objectives. Additionally, if there is any documentation available covering these aspects, please share it with us.

**Comment by jrose-signal** [comment]
I'm afraid we don't have real high-level docs, as covered by the longstanding #152. libsignal is a library for Signal-the-app first, so integration from the ground up isn't something we spend a lot of time on. That said, this question would be a good fit for the Development section of https://community.signalusers.org/.
