### ISSUE TITLE
Checksum Does Not Match [release 0.41.2] 

### ISSUE THREAD

**Issue by reem-alhussain** [signalapp/libsignal#564]
The provided `LIBSIGNAL_FFI_PREBUILD_CHECKSUM` doesn't match!

``` swift
AssertionError: expected 3fd72aa93ddf582f0aaecc3e649081df36ae562f5be22d18b69d2d3233bfbe96, actual 8a3bb19afe41e3d4b55b0e19664889fba46641e51a2662e2d527c28ea661eace
Command PhaseScriptExecution failed with a nonzero exit code
```

Release: 0.41.2

**Comment by jrose-signal** [comment]
I'm not sure where you got `3fd72aa93ddf582f0aaecc3e649081df36ae562f5be22d18b69d2d3233bfbe96` from. `8a3bb19afe41e3d4b55b0e19664889fba46641e51a2662e2d527c28ea661eace` is the checksum listed on the release.
