### ISSUE TITLE
Anyone about using Nostr on Signal?

### ISSUE THREAD

**Issue by lucasnuic** [signalapp/libsignal#570]
I think it makes sense for app signal to have an integrated communication layer in nostr system.

According to the documentation this appears here: *"Nostr is a simple, open protocol that enables global, decentralized, and censorship-resistant social media."*

The nostr network protocol looks a lot like solid-project and the signal would have huge commercial advantage eith this.

**Comment by jrose-signal** [comment]
Hi, I'm afraid we don't take feature requests on GitHub. Please file a request at https://support.signal.org, or bring it up on the unofficial community forums at http://community.signalusers.org.
