### ISSUE TITLE
[Feature Request] Synchronize group wallpaper and chat bubble color

### ISSUE THREAD

**Issue by lukeh990** [signalapp/libsignal#572]
Hello, I have no idea if this topic has been previously discussed but I can’t find anything just searching the closed issues. 

My idea: In the same way that group avatars and names are synced between devices, could a group share a wallpaper and chat bubble color?

Reasoning: Mainly I think it would be cool. But other than that I think it would be helpful to make the appearance across devices uniform.

I do think to make this work each client would have to activate the feature manually in each group.

**Comment by jrose-signal** [comment]
Sorry, this repository is specifically for the lower-level library that provides cryptographic and networking functionality across all Swift's client apps. Feature requests should go to https://support.signal.org, or the unofficial community forums at https://community.signalusers.org.
