### ISSUE TITLE
script_phases: Unrecognized option(s) `always_out_of_date` in script phase `Download libsignal-ffi if not in cache`

### ISSUE THREAD

**Issue by amirvatani** [signalapp/libsignal#573]
**my Podfile :** 

  use_expo_modules!
  config = use_native_modules!

  use_frameworks!
  
  pod 'LibSignalClient', :git => 'https://github.com/signalapp/libsignal.git'
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git' , :modular_headers => true 
  ENV['LIBSIGNAL_FFI_PREBUILD_CHECKSUM'] = 'efa1ba4cef14c220714fbc657bd104b5c01df0b9e15a33836c112278150460d6'
          

**Error while pod install :**

Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: The `LibSignalClient` pod failed to validate due to 1 error:
    - ERROR | [iOS] script_phases: Unrecognized option(s) `always_out_of_date` in script phase `Download libsignal-ffi if not in cache`. Available options are `name, script, shell_path, input_files, output_files, input_file_lists, output_file_lists, show_env_vars_in_log, execution_position, dependency_file`.

pod install --repo-update --ansi exited with non-zero code: 1

could you please help, i am using react native Expo 
react-native-cli: 2.0.1
react-native: 0.73.4
 expo SDK Version: "50.0.0"
<img width="1208" alt="Screenshot 2024-05-06 at 15 17 59" src="https://github.com/signalapp/libsignal/assets/29254313/73022ad5-d57f-438d-b366-2244f15ae3c0">

**Comment by jrose-signal** [comment]
You'll need a newer version of CocoaPods that understands that option. Sorry for the inconvenience!

**Comment by amirvatani** [comment]
@jrose-signal 🙏🏻 Thanks
