### ISSUE TITLE
Use Signal API to create new rooms

### ISSUE THREAD

**Issue by yasinishyn** [signalapp/libsignal#580]
We are building an app that supposed to be dependant to Signal.
We want to be able to automatically create a room and invite people there.

Is there an open API for this and where can we find it's documentation?

**Comment by scottslewis** [comment]
I would like to be able to use the libsignal code to do this and address other third-party use cases as well.   

I would be willing to contribute API documentation, examples, tutorials, etc. for this and other use cases (programmatically defined groups/rooms).

Another question:   I would expect that the Signal-Server repo would have /examples/tutorials/etc also...as I would imagine that it already supports this functionality and wanted to use the source to figure it out.   But the Signal-Server repo doesn't have an Issues list (e.g. for build/releng information) nor any published version of the docs.

Feel free to contact me directly at scottslewis at gmail.com if there is a way that I can/could contribute API design/tooling/docs/examples/tutorials/etc to either libsignal or Signal-Server repos.  I've been a project lead at Eclipse Foundation for long time and contributed to multiple open source projects so I'm willing to sign contributor agreements 
 and even join team if needed.
