### ISSUE TITLE
JNI library loading fails on Mac Intel with Corretto JDK 17.0.12

### ISSUE THREAD

**Issue by guiyanakuang** [signalapp/libsignal#584]
https://github.com/signalapp/libsignal/blob/ee321f2697666fce90f793a876226cad830585b3/java/shared/java/org/signal/libsignal/internal/Native.java#L70-L81

On Mac Intel machines running Corretto JDK 17.0.12, `System.getProperty("os.arch")` returns "x86_64" instead of the expected "amd64". This causes the `loadLibrary` method to fail to find the native library.

**Comment by jrose-signal** [comment]
Oof, that's unfortunate. Are you using libsignal from Maven, or building your own?

**Comment by guiyanakuang** [comment]
This issue appears in the latest version 0.54.1, downloaded from Maven.

**Comment by jrose-signal** [comment]
Ah yeah, I'm not surprised that it's happening there, it's just that if you were building your own anyway we could have merely made this a build-time option. Will ponder the best way to address this; thanks for reporting it!

**Comment by jrose-signal** [comment]
Should be fixed (via manual special-casing) in v0.54.2, let us know if that's still failing!

**Comment by guiyanakuang** [comment]
> Should be fixed (via manual special-casing) in v0.54.2, let us know if that's still failing!

@jrose-signal , Using various languages and then coming back to Java always makes one forget its intricacies, 😅 Using `==` to compare strings always fails.

**Comment by jrose-signal** [comment]
🤦 Thank you for catching that, if only we had. *Next* tag, then.

**Comment by jrose-signal** [comment]
Okay, please try again with v0.54.3!

**Comment by guiyanakuang** [comment]
Thank you for fixing this issue.
