### ISSUE TITLE
Libsignal typescript

### ISSUE THREAD

**Issue by AlexVorobiov** [signalapp/libsignal#588]
Hey everyone,

I’m trying to figure out how to implement the Signal protocol in TypeScript. I’m using @signalapp/libsignal-client, but I can’t find any documentation on how to implement it. I think my current problem is that I always receive PreKeySignalMessage, but I believe I need SignalMessage.

[my example](https://github.com/AlexVorobiov/signal-implementation/blob/main/index.ts)

Thanks for any help.

**Comment by jrose-signal** [comment]
Questions like this are better suited for the Development section of the unofficial forums at <http://community.signalusers.org>. (We are a little underdocumented, heh.)

**Comment by LeoInCode** [comment]
@AlexVorobiov, I have the same doubt about this. I'm trying find some example on the internet, but I can't. How about your progress?
