### ISSUE TITLE
More granular control over which media types users are able to receive/send in a message

### ISSUE THREAD

**Issue by simonsan** [signalapp/libsignal#592]
I would like to propose an enhancement for Signal that would significantly improve user experience regarding message control. And I believe this is not yet implemented in the protocol. The idea is to allow users to **disallow specific contacts from sending certain types of messages**, particularly voice messages.

### Feature Request: Block Voice Messages from Specific Contacts

**Overview:**
Currently, Signal allows users to block messages from contacts, but it would be beneficial to extend this functionality. Specifically, I suggest implementing a feature where users can prevent designated contacts from sending voice messages entirely. This could enhance privacy and reduce unwanted interactions.

**Proposed Functionality:**
- **Disallow Voice Messages:** When a user selects a contact to block from sending voice messages, that contact would receive an error or notification indicating that they cannot send voice messages to the user.
- **Disallow Other Media Types:** When a user selects a contact to block from sending messages with other media types, that contact would receive an error or notification indicating that they cannot send that media type to the user.
- **User Experience:** For the blocked contact, the option to record and send a voice message should not appear in the chat interface. This would streamline communication and prevent misunderstandings.

**Benefits:**
- **Enhanced Privacy:** Users can manage their interactions more effectively, ensuring that only desired forms of communication are allowed.
- **Reduced Frustration:** This feature would minimize unwanted interruptions and help maintain a more controlled messaging environment.

I believe this addition would align with Signal's commitment to user privacy and security while providing more granular control over communication preferences. Thank you for considering this feature request!

**EDIT:** This can also be useful as a general/global setting, where you would want to say, that you don't want to opt in/want to opt out of certain media types in messages completely. Like the stories feature for example, so you wouldn't need to set it on a per-contact basis. But you still would be able to do that, in case you only would apply this limitation on a certain contact.

**Comment by jrose-signal** [comment]
Sorry, this repository is specifically for the lower-level library that provides cryptographic and networking functionality across all Signal's client apps. Feature requests should go to https://support.signal.org/, or the unofficial community forums at https://community.signalusers.org/.
