### ISSUE TITLE
Post-Quantum Support in libsignal-client Java Library?

### ISSUE THREAD

**Issue by nazir92** [signalapp/libsignal#593]
I’ve read that Signal has already implemented post-quantum cryptography in their apps.However, I noticed that the current version of the libsignal-client library ([here](https://mvnrepository.com/artifact/org.signal/libsignal-client)) doesn’t seem to expose this post-quantum support yet. Is there any information about when this feature will be available in the official Java library? Or is it already supported, and I’m missing something?

**Comment by jrose-signal** [comment]
The general-use entry point is KEMKeyPair, which generates Kyber1024 keys (note: not quite the same as the NIST-finalized ML-KEM). The use of [PQXDH](https://signal.org/blog/pqxdh/) comes from using a KyberPreKeyStore and your server providing Kyber keys in PreKeyBundles.

**Comment by nazir92** [comment]
Hi @jrose-signal,
Thank you for your response. I reviewed the PreKeyBundle class but couldn’t locate any functionality specifically related to signed one-time PQKEM prekeys and their signatures. Does this mean the current implementation only creates sessions using the signed last-resort PQKEM prekey, its signature, and identifier?

`public PreKeyBundle(int registrationId, int deviceId, int preKeyId, ECPublicKey preKeyPublic, int signedPreKeyId, ECPublicKey signedPreKeyPublic, byte[] signedPreKeySignature, IdentityKey identityKey, int kyberPreKeyId, KEMPublicKey kyberPreKeyPublic, byte[] kyberPreKeySignature)`

**Comment by dreirund** [comment]
It seems that signal will enforce PQXDH in the near future:

* https://support.signal.org/hc/en-us/articles/8997185514138-Re-connect-your-primary-device-to-continue-using-Signal-Desktop (at the bottom),
* Signal desktop with version 7.48 starts to show a warning that a re-link should be done soon (and refers to the above URL).
