### ISSUE TITLE
jni: Add better typing for handles

### ISSUE THREAD

**Issue by jack-signal** [signalapp/libsignal#60]
Right now we just pass bare longs encoding the raw pointer and hope that Java and Rust agree on the type.

Instead pass the objects themselves, and write a helper that first calls `check_jobject_type` which verifies the passed object is the correct type, then calls `nativeHandle()` on that object to get the handle, then cast that to a pointer to a Rust type.

This has the downside of adding several more JVM invocations *per argument* which might add up. Probably best to wait until we have full system benchmarking available to make sure this is not too expensive.

**Comment by jrose-signal** [comment]
For both JNI and FFI we may also want to take a leaf from Neon's book and either put everything in a RefCell or distinguish between immutable and mutable handles (the latter of which can use RefCell) at the same time we add type checking.

**Comment by jrose-signal** [comment]
We switched to this basic approach for Node, so it makes sense to do it for Java as well.
