### ISSUE TITLE
storage API simplification

### ISSUE THREAD

**Issue by 2ob** [signalapp/libsignal#85]
`IdentityKeyStore` has a method with the following signature:
https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/storage/traits.rs#L41-L45

Can the return type of this method be simplified to `Result<IdentityKey>`, where implementations of `IdentityKeyStore` would return `Err(SignalProtocolError::InvalidIdentityKey)` (wihch would have to be added as an `enum` value) or `Err(SignalProtocolError::UntrustedIdentity)` (which already exists) if no trusted identity key is found? This would more closely mirror what the in-memory implementation of `PreKeyStore` does: https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/storage/inmem.rs#L111-L117

The same can be done here
https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/storage/traits.rs#L79-L84 where users could return an `Err` containing https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/error.rs#L57 instead of `Ok(Option::None)` when no session is found and in `SenderKeyStore` https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/storage/traits.rs#L103-L107 where implementing methods could return an `Err` containing https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/error.rs#L54 instead of `Ok(Option::None)` when no sender key is found.

**Comment by jrose-signal** [comment]
On the one hand that lines up with what signalapp/libsignal-client#82 basically had to do to match the existing Java behavior; on the other hand it means we have a mix of fatal and non-fatal errors. So I could see an argument for either API.
